#ifndef __EIDTYPESKILL_H__
#define __EIDTYPESKILL_H__

enum eIDTypeSkill
{
	NINJA_THROW_STAR,
	NINJA_FLAMES,
	NINJA_WINDMIL_STAR,
	NINJA_SWORD,
	SWORD_ENEMY_THROW,
	BULLET_MACHINE_GUN,
	ROCKET_ENEMY,
	BULLET_BOSS,
};
#endif