#ifndef eObjectID_h
#define eObjectID_h
enum eObjectID
{
	TILE_BASE,
	VIRTUAL_OBJECT_WALL,
	NINJA,
	SWORD_NINJA,
	ENEMY_ROCKET,
	BULLET_ENEMY,
	GIF_BUTERFLY, GIF_BIRD,
	OBJECT_5_POWER, OBJECT_10_POWER, OBJECT_500_POINT, OBJECT_1000_POINT, OBJECT_FLAMES, OBJECT_THROW_STAR, OBJECT_TIME_FREEZE, OBJECT_WINDMIL_STAR, OBJECT_HEALTH,
	ENEMY_SWORD,
	ENEMY_RUN,
	ENEMY_THROW_SWORD,
	ENEMY_BROWN_BAT,
	ENEMY_EAGLE,
	ENEMY_PANTHER,
	ENEMY_MACHINE_GUN,
	SWORD_ENEMY,
	BOSS_3, // Boss
	BULLET_BOSS3,
	TILE_BACKGROUND,
	VIRTUAL_OBJECT_CLIMB,
};
#endif