#ifndef EObjectState_h
#define EObjectState_h
enum eObjectState
{
	STATE_ALIVE_IDLE = 0,
	STATE_ALIVE_MOVE = 1,
	STATE_POPUP, STATE_SHUTDOWN,
	STATE_FIGHT,
	STATE_JUMP,
	STATE_BEFORE_DEATH,
	STATE_DEATH,
	STATE_BOSS_DEATH,
	STATE_SHOOTING,

	STATE_NINJA_RUN,
	STATE_NINJA_DEAD,
	STATE_NINJA_HIT,
	STATE_NINJA_IDLE,
	STATE_NINJA_JUMP,
	STATE_NINJA_FALL,
	STATE_NINJA_CLIMB,
	STATE_NINJA_SIT,
	STATE_NINJA_SIT_HIT,
	STATE_NINJA_JUMP_HIT,
	STATE_NINJA_SKILL,
	STATE_NINJA_HANG,

	STATE_ALIVE_MOVE_REVERSE,
	STATE_ALIVE_MOVE_A_LINE,
};
#endif
