#ifndef __ESOUNDID_H__
#define	__ESOUNDID_H__
enum eSoundID
{
	SOUND_NINJA_HIT,
	SOUND_NINJA_JUMP,
	SOUND_NINJA_HITTED,
	SOUND_NINJA_COLECT,
	SOUND_NINJA_CLIMB,
	SOUND_THROW_STAR,
	SOUND_WINDMIL_STAR,
	SOUND_EXPLOSION,
	SOUND_ROCKET,
	SOUND_BOSS,
	SOUND_BACKGROUND_1,
	SOUND_BACKGROUND_2,
	SOUND_DEAD,
};
#endif