#ifndef ESPRITEID_H
#define ESPRITEID_H
enum eSpriteID
{
	SPRITE_MAP_1 = 1,
	SPRITE_MAP_2 = 2,
	SPRITE_MAP_3 = 3,

	SPRITE_NINJA_RUN,
	SPRITE_NINJA_HIT,
	SPRITE_NINJA_JUMP,
	SPRITE_NINJA_IDLE,
	SPRITE_NINJA_SIT,
	SPRITE_NINJA_SIT_HIT,
	SPRITE_NINJA_JUMP_HIT,
	SPRITE_NINJA_SKILL,
	SPRITE_NINJA_CLIMB,

	SPRITE_FLAMES,
	SPRITE_THROW_STAR,
	SPRITE_WINDMIL_STAR,
	SPRITE_FREEZE,
	SPRITE_HEALTH,
	SPRITE_500_POINT,
	SPRITE_1000_POINT,
	SPRITE_5_POWER,
	SPRITE_10_POWER,

	SPRITE_GIF_BIRD,
	SPRITE_GIF_BUTERFLY,
	SPRITE_ENEMY_SWORD,
	SPRITE_ENEMY_RUN,

	SPRITE_SKILL_WINDMIL_STAR,
	SPRITE_SKILL_THROW_STAR,
	SPRITE_SKILL_FLAMES,
	SPRITE_EXPLOSION,
};
#endif